kind: pipeline
type: docker
name: default

- name: docker  
  image: plugins/docker
  settings:
    registry: registry.ikjpz.com
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

#- name: send
  #image: plugins/webhook
  #settings:
    #urls:
      #from_secret: update_hook
