version: "3.7"
services:
  bot:
    build: .
    image: registry.ikjpz.com/ikjpz.com/rules_bot
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://rules-bot:${POSTGRES_PASSWORD}@db/rules-bot
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      RUST_LOG: info
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: rules-bot

volumes:
  db:
